### PR TITLE
Game logic

### PR DESCRIPTION
**Pull request by 0x1100010010**
We made the following implementations:

  - Created Game Logic Module in a separate file (Module GameLogic
  - Created separate fie for the player class (class Board)
  - Modularized the project
  - Optimized Code
  - Created Additional checks in previous logic

### CODE REVIEW

**Review by voscarmv — CHANGES_REQUESTED** [review]
# Impressive work, team! 🖥️ 👀 ✨ 

- Excellent work with your game logic. The game works!

## However, some changes are still required... 🧰 🔨 🔧 

- I really like how you divided your game logic into modules in the lib directory. However, you are indirectly calling `puts` and `gets` functions from within the `game_logic.rb` file. I noticed you put the game loop inside your `game_logic` directory. Actually, the game loop should go inside the `main.rb` file, and all the helper functions you use inside the game loop should be inside the `game_logic.rb` file. So please, just invert the content of these two files, `main.rb` and `game_logic.rb`, and take note of not using (directly or indirectly) `gets.chomp` or `puts` in your `lib` files.

If you need any clarifications on how to do this, feel free to contact me on slack. I'll be available all day long!

### Submit these changes and request a new code review! 😄 👍 

### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier) 🧑‍💻🗨️🧑‍💻 
# Happy Hacking! 🧠 ⌨️ 🖱️ 🖥️

**Review by krys2fa — CHANGES_REQUESTED** [review]
## Awesome work @bashforger and @Zappat0n 👏 
Kudos for having a decent README already in place even though it is not required at this stage.  👍
Also, good job on implementing the changes suggested by the previous TSE. However, it seems your changes broke your code.
### Status: Changes Required ♻️ 

- [REQUIRED ] The game quits unexpectedly when a player makes an input. The error message is seen below:
```
... check_winner.rb:12:in `all?': wrong number of arguments (given 1, expected 0) (ArgumentError)
```

- [REQUIRED] The game accepts numbers as well as space as player names. Let's validate the names so the game is easier to play.

- [REQUIRED] Please state in your instructions how a player can make a move on the board. Not all players will know immediately to make a move by typing a coordinate (like `a1`) to place a marker in a particular cell.

That's all for now. Please request for another review after implementing the changes.

Happy Coding 🖥️  😃 

###### You can contact me on slack (Chris Amanor) for any clarification.

**Review by andresporras3423 — CHANGES_REQUESTED** [review]
### Status: Changes Required :recycle:
**Hello Angel Barros Pazos & Adeel Mohammad** 
Nice job so far :muscle:  :muscle:
Your project meets most of the requirements :clap: :clap: :clap:  
Just a couple of details to improve before you can go ahead:

- [x] Fix all rubocop offenses
- [x] In the Game class, your methods "right_move?" and "move" should be private
 
Please request another review once you are ready! :+1: 
 
Happy coding :relaxed:
 
Oscar Andrés Russi Porras

**Review by tirthajyoti-ghosh — APPROVED** [review]
# Approved ✅

## You have done an incredible job completing this milestone 👏🧨💪! Just perfect 💯! 

### You have met all the requirements of this milestone. Go ahead and merge it! Onto the next milestone 🚀 !

Happy coding 👨‍💻 

<hr>

**Tirthajyoti Ghosh**

[GitHub](https://github.com/tirthajyoti-ghosh) | [LinkedIn](https://www.linkedin.com/in/tirthajyoti-ghosh/) | [Twitter](https://twitter.com/terrific_ghosh)

**Pull request merged**
